### ISSUE TITLE
go get github.com/romainmenke/simple-guetzli

### ISSUE THREAD

**Issue by sunatthegilddotcom** [romainmenke/simple-guetzli#6]
@romainmenke I am trying to download the simple-guetzli via the above command on redhat 6 (uname -a
Linux redhatcompression 2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Mar 21 12:19:18 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
) after  the packages are downloaded.  see the partial du -a result 

2052    ./src/github.com
2168    ./src
2172    .
=================================
Is there anything we need to do furthure?  Thank you very much!

**Comment by romainmenke** [comment]
It appears I forgot to update vendored dependencies after the last couple of changes. Should be fixed now.

**Comment by sunatthegilddotcom** [comment]
@romainmenke Thank you very much for your help!

**Comment by romainmenke** [comment]
@sunatthegilddotcom I will close this issue, feel free to reopen if there still is a problem with `go get ...`

**Comment by sunatthegilddotcom** [comment]
I got this error.

# github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:16:38: error: import file ‘github.com/alecthomas/template/parse’ not found
  "github.com/alecthomas/template/parse"
                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:25:12: error: expected package
  node parse.Node // current node, for errors
            ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:69:30: error: expected package
 func (s *state) at(node parse.Node) {
                              ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:162:51: error: expected package
 func (s *state) walk(dot reflect.Value, node parse.Node) {
                                                   ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:165:13: error: expected package
  case *parse.ActionNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:172:13: error: expected package
  case *parse.IfNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:174:13: error: expected package
  case *parse.ListNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:178:13: error: expected package
  case *parse.RangeNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:180:13: error: expected package
  case *parse.TemplateNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:182:13: error: expected package
  case *parse.TextNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:186:13: error: expected package
  case *parse.WithNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:195:39: error: expected package
 func (s *state) walkIfOrWith(typ parse.NodeType, dot reflect.Value, pipe *parse.PipeNode, list, elseList *parse.ListNode) {
                                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:195:80: error: expected package
 func (s *state) walkIfOrWith(typ parse.NodeType, dot reflect.Value, pipe *parse.PipeNode, list, elseList *parse.ListNode) {
                                                                                ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:195:112: error: expected package
 func (s *state) walkIfOrWith(typ parse.NodeType, dot reflect.Value, pipe *parse.PipeNode, list, elseList *parse.ListNode) {
                                                                                                                ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:243:54: error: expected package
 func (s *state) walkRange(dot reflect.Value, r *parse.RangeNode) {
                                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:304:57: error: expected package
 func (s *state) walkTemplate(dot reflect.Value, t *parse.TemplateNode) {
                                                         ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:327:60: error: expected package
 func (s *state) evalPipeline(dot reflect.Value, pipe *parse.PipeNode) (value reflect.Value) {
                                                            ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:345:42: error: expected package
 func (s *state) notAFunction(args []parse.Node, final reflect.Value) {
                                          ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:351:58: error: expected package
 func (s *state) evalCommand(dot reflect.Value, cmd *parse.CommandNode, final reflect.Value) reflect.Value {
                                                          ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:354:13: error: expected package
  case *parse.FieldNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:356:13: error: expected package
  case *parse.ChainNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:358:13: error: expected package
  case *parse.IdentifierNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:361:13: error: expected package
  case *parse.PipeNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:364:13: error: expected package
  case *parse.VariableNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:370:13: error: expected package
  case *parse.BoolNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:372:13: error: expected package
  case *parse.DotNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:374:13: error: expected package
  case *parse.NilNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:376:13: error: expected package
  case *parse.NumberNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:378:13: error: expected package
  case *parse.StringNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:389:46: error: expected package
 func (s *state) idealConstant(constant *parse.NumberNode) reflect.Value {
                                              ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:415:62: error: expected package
 func (s *state) evalFieldNode(dot reflect.Value, field *parse.FieldNode, args []parse.Node, final reflect.Value) reflect.Value {
                                                              ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:415:86: error: expected package
 func (s *state) evalFieldNode(dot reflect.Value, field *parse.FieldNode, args []parse.Node, final reflect.Value) reflect.Value {
                                                                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:420:62: error: expected package
 func (s *state) evalChainNode(dot reflect.Value, chain *parse.ChainNode, args []parse.Node, final reflect.Value) reflect.Value {
                                                              ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:420:86: error: expected package
 func (s *state) evalChainNode(dot reflect.Value, chain *parse.ChainNode, args []parse.Node, final reflect.Value) reflect.Value {
                                                                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:430:68: error: expected package
 func (s *state) evalVariableNode(dot reflect.Value, variable *parse.VariableNode, args []parse.Node, final reflect.Value) reflect.Value {
                                                                    ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:430:95: error: expected package
 func (s *state) evalVariableNode(dot reflect.Value, variable *parse.VariableNode, args []parse.Node, final reflect.Value) reflect.Value {
                                                                                               ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:444:71: error: expected package
 func (s *state) evalFieldChain(dot, receiver reflect.Value, node parse.Node, ident []string, args []parse.Node, final reflect.Value) reflect.Value {
                                                                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:444:106: error: expected package
 func (s *state) evalFieldChain(dot, receiver reflect.Value, node parse.Node, ident []string, args []parse.Node, final reflect.Value) reflect.Value {
                                                                                                          ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:453:60: error: expected package
 func (s *state) evalFunction(dot reflect.Value, node *parse.IdentifierNode, cmd parse.Node, args []parse.Node, final reflect.Value) reflect.Value {
                                                            ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:453:86: error: expected package
 func (s *state) evalFunction(dot reflect.Value, node *parse.IdentifierNode, cmd parse.Node, args []parse.Node, final reflect.Value) reflect.Value {
                                                                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:453:105: error: expected package
 func (s *state) evalFunction(dot reflect.Value, node *parse.IdentifierNode, cmd parse.Node, args []parse.Node, final reflect.Value) reflect.Value {
                                                                                                         ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:466:74: error: expected package
 func (s *state) evalField(dot reflect.Value, fieldName string, node parse.Node, args []parse.Node, final, receiver reflect.Value) reflect.Value {
                                                                          ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:466:93: error: expected package
 func (s *state) evalField(dot reflect.Value, fieldName string, node parse.Node, args []parse.Node, final, receiver reflect.Value) reflect.Value {
                                                                                             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:524:60: error: expected package
 func (s *state) evalCall(dot, fun reflect.Value, node parse.Node, name string, args []parse.Node, final reflect.Value) reflect.Value {
                                                            ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:524:92: error: expected package
 func (s *state) evalCall(dot, fun reflect.Value, node parse.Node, name string, args []parse.Node, final reflect.Value) reflect.Value {
                                                                                            ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:622:69: error: expected package
 func (s *state) evalArg(dot reflect.Value, typ reflect.Type, n parse.Node) reflect.Value {
                                                                     ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:625:13: error: expected package
  case *parse.DotNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:627:13: error: expected package
  case *parse.NilNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:632:13: error: expected package
  case *parse.FieldNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:633:58: error: expected package
   return s.validateType(s.evalFieldNode(dot, arg, []parse.Node{n}, zero), typ)
                                                          ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:634:13: error: expected package
  case *parse.VariableNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:636:13: error: expected package
  case *parse.PipeNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:638:13: error: expected package
  case *parse.IdentifierNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:640:13: error: expected package
  case *parse.ChainNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:665:51: error: expected package
 func (s *state) evalBool(typ reflect.Type, n parse.Node) reflect.Value {
                                                   ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:667:23: error: expected package
  if n, ok := n.(*parse.BoolNode); ok {
                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:676:53: error: expected package
 func (s *state) evalString(typ reflect.Type, n parse.Node) reflect.Value {
                                                     ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:678:23: error: expected package
  if n, ok := n.(*parse.StringNode); ok {
                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:687:54: error: expected package
 func (s *state) evalInteger(typ reflect.Type, n parse.Node) reflect.Value {
                                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:689:23: error: expected package
  if n, ok := n.(*parse.NumberNode); ok && n.IsInt {
                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:698:62: error: expected package
 func (s *state) evalUnsignedInteger(typ reflect.Type, n parse.Node) reflect.Value {
                                                              ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:700:23: error: expected package
  if n, ok := n.(*parse.NumberNode); ok && n.IsUint {
                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:709:52: error: expected package
 func (s *state) evalFloat(typ reflect.Type, n parse.Node) reflect.Value {
                                                    ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:711:23: error: expected package
  if n, ok := n.(*parse.NumberNode); ok && n.IsFloat {
                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:720:54: error: expected package
 func (s *state) evalComplex(typ reflect.Type, n parse.Node) reflect.Value {
                                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:721:23: error: expected package
  if n, ok := n.(*parse.NumberNode); ok && n.IsComplex {
                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:730:62: error: expected package
 func (s *state) evalEmptyInterface(dot reflect.Value, n parse.Node) reflect.Value {
                                                              ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:733:13: error: expected package
  case *parse.BoolNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:735:13: error: expected package
  case *parse.DotNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:737:13: error: expected package
  case *parse.FieldNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:739:13: error: expected package
  case *parse.IdentifierNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:741:13: error: expected package
  case *parse.NilNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:744:13: error: expected package
  case *parse.NumberNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:746:13: error: expected package
  case *parse.StringNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:748:13: error: expected package
  case *parse.VariableNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:750:13: error: expected package
  case *parse.PipeNode:
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:774:35: error: expected package
 func (s *state) printValue(n parse.Node, v reflect.Value) {
                                   ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:11:38: error: import file ‘github.com/alecthomas/template/parse’ not found
  "github.com/alecthomas/template/parse"
                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:29:8: error: expected package
  *parse.Tree
        ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:108:57: error: expected package
 func (t *Template) AddParseTree(name string, tree *parse.Tree) (*Template, error) {
                                                         ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:200:56: error: expected package
 func (t *Template) associate(new *Template, tree *parse.Tree) (bool, error) {
                                                        ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:37:19: error: argument 1 must be a slice
  s.vars = append(s.vars, variable{name, value})
                   ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:139:6: error: reference to undefined field or method ‘Tree’
  if t.Tree == nil || t.Root == nil {
      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:139:23: error: reference to undefined field or method ‘Root’
  if t.Tree == nil || t.Root == nil {
                       ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:142:11: error: reference to undefined field or method ‘Tree’
    if tmpl.Tree == nil || tmpl.Root == nil {
           ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:142:31: error: reference to undefined field or method ‘Root’
    if tmpl.Tree == nil || tmpl.Root == nil {
                               ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:156:21: error: reference to undefined field or method ‘Root’
  state.walk(value, t.Root)
                     ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:173:18: error: reference to undefined name ‘parse’
   s.walkIfOrWith(parse.NodeIf, dot, node.Pipe, node.List, node.ElseList)
                  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:175:3: error: range clause must have array, slice, string, map, or channel type
   for _, node := range node.Nodes {
   ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:187:18: error: reference to undefined name ‘parse’
   s.walkIfOrWith(parse.NodeWith, dot, node.Pipe, node.List, node.ElseList)
                  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:172:2: error: duplicate type in switch
  case *parse.IfNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:174:2: error: duplicate type in switch
  case *parse.ListNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:178:2: error: duplicate type in switch
  case *parse.RangeNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:180:2: error: duplicate type in switch
  case *parse.TemplateNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:182:2: error: duplicate type in switch
  case *parse.TextNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:186:2: error: duplicate type in switch
  case *parse.WithNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:203:13: error: reference to undefined name ‘parse’
   if typ == parse.NodeWith {
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:312:14: error: expected pointer
  newState := *s
              ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:332:2: error: range clause must have array, slice, string, map, or channel type
  for _, cmd := range pipe.Cmds {
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:339:2: error: range clause must have array, slice, string, map, or channel type
  for _, variable := range pipe.Decl {
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:356:2: error: duplicate type in switch
  case *parse.ChainNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:358:2: error: duplicate type in switch
  case *parse.IdentifierNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:361:2: error: duplicate type in switch
  case *parse.PipeNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:364:2: error: duplicate type in switch
  case *parse.VariableNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:372:2: error: duplicate type in switch
  case *parse.DotNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:374:2: error: duplicate type in switch
  case *parse.NilNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:376:2: error: duplicate type in switch
  case *parse.NumberNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:378:2: error: duplicate type in switch
  case *parse.StringNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:627:2: error: duplicate type in switch
  case *parse.NilNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:632:2: error: duplicate type in switch
  case *parse.FieldNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:634:2: error: duplicate type in switch
  case *parse.VariableNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:636:2: error: duplicate type in switch
  case *parse.PipeNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:638:2: error: duplicate type in switch
  case *parse.IdentifierNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:640:2: error: duplicate type in switch
  case *parse.ChainNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:735:2: error: duplicate type in switch
  case *parse.DotNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:737:2: error: duplicate type in switch
  case *parse.FieldNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:739:2: error: duplicate type in switch
  case *parse.IdentifierNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:741:2: error: duplicate type in switch
  case *parse.NilNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:744:2: error: duplicate type in switch
  case *parse.NumberNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:746:2: error: duplicate type in switch
  case *parse.StringNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:748:2: error: duplicate type in switch
  case *parse.VariableNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:750:2: error: duplicate type in switch
  case *parse.PipeNode:
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:99:4: error: reference to undefined field or method ‘Tree’
  nt.Tree = t.Tree
    ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:99:13: error: reference to undefined field or method ‘Tree’
  nt.Tree = t.Tree
             ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:113:4: error: reference to undefined field or method ‘Tree’
  nt.Tree = tree
    ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:172:16: error: reference to undefined name ‘parse’
  trees, err := parse.Parse(t.name, text, t.leftDelim, t.rightDelim, t.parseFuncs, builtins)
                ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:177:6: error: invalid type for range clause
  for name, tree := range trees {
      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:188:8: error: reference to undefined field or method ‘Tree’
    tmpl.Tree = tree
        ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:177:2: error: range clause must have array, slice, string, map, or channel type
  for name, tree := range trees {
  ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:206:17: error: reference to undefined name ‘parse’
   oldIsEmpty := parse.IsEmptyTree(old.Root)
                 ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:206:38: error: reference to undefined field or method ‘Root’
   oldIsEmpty := parse.IsEmptyTree(old.Root)
                                      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:207:17: error: reference to undefined name ‘parse’
   newIsEmpty := parse.IsEmptyTree(tree.Root)
                 ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:332:6: error: invalid type for range clause
  for _, cmd := range pipe.Cmds {
      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/exec.go:339:6: error: invalid type for range clause
  for _, variable := range pipe.Decl {
      ^
.go/src/github.com/romainmenke/simple-guetzli/vendor/github.com/alecthomas/template/template.go:177:6: error: invalid type for range clause
  for name, tree := range trees {
      ^

**Comment by romainmenke** [comment]
I just tested it in a docker image to make sure everything is included and that works.

`docker run -it golang /bin/bash`
`go get github.com/romainmenke/simple-guetzli`
`go install github.com/romainmenke/simple-guetzli`
`simple-guetzli --help`

Are you sure that you have updated since my last commit? These dependencies that are missing, are the ones I added.

**Comment by romainmenke** [comment]
@sunatthegilddotcom If you could let me know if this error persists after I updated the vendored files, that would be really helpful. 

Also try `go get -u github.com/romainmenke/simple-guetzli`

**Comment by sunatthegilddotcom** [comment]
@romainmenke  I tested the Docker.  It works fine. Let me do some more research.  There must be some thing wrong in my server.  BTW, the server is Redhat server.

**Comment by romainmenke** [comment]
@sunatthegilddotcom The dependencies that seem to cause the problem are only used to give a color to the logs in `--verbose` mode for each Guetzli process. This was something I thought would be useful but if this causes compatibility issues I would be happy to remove it.

You could try replacing https://github.com/romainmenke/simple-guetzli/blob/master/main.go#L130
```
_ = index
j.color = func(str string) string {
	return str
}
```

**Comment by atomissariyaporn** [comment]
Get
