### ISSUE TITLE
Copying EXIF/IPTC/XMP data

### ISSUE THREAD

**Issue by rremo** [romainmenke/simple-guetzli#7]
Thank you very much for the "helper"!
Nice tool for testing.

Running following command:
simple-guetzli --verbose -q90 -m24000 -t4 ./src_in ./src_out ./logging

![jpeg-exif-guetzli](https://cloud.githubusercontent.com/assets/16868650/26029169/0f2339bc-382f-11e7-9530-04db6d14b7b2.png)
It will be compressed, but the EXIF/IPTC/XMP data get lost. This is normal with guetzli...

It would be nice if you can add (like) exiftool and copying the data.

**Comment by romainmenke** [comment]
@rremo  The focus of this tool is to provide smaller images for websites. Adding exif/metadata defeats the purpose, sorry
